#!/bin/bash

DBUSER=postgres
DBHOST=localhost
DBPORT=5433
DBNAME=vrptools_test

make clean all
make -f Makefile.library PGVER=9.3 clean all
sudo make -f Makefile.library PGVER=9.3 install

dropdb  -h $DBHOST -U $DBUSER -p $DBPORT $DBNAME
createdb -h $DBHOST -U $DBUSER -p $DBPORT $DBNAME

psql -h $DBHOST -U $DBUSER -p $DBPORT $DBNAME < muni-b/muni-b.sql

psql -h $DBHOST -U $DBUSER -p $DBPORT $DBNAME -c "create extension vrptools with schema public"

psql -h $DBHOST -U $DBUSER -p $DBPORT $DBNAME -c "alter database $DBNAME set search_path to data, public"

psql -h $DBHOST -U $DBUSER -p $DBPORT $DBNAME -c "select * from  vrp_trashcollection( 'select * from containers limit 10', 'select * from other_locs', 'select * from vehicles', 'select * from distance_matrix')"
